apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: ingress-nginx
spec:
  type: ClusterIP
  ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    app: consumer
status:
  loadBalancer: {}
