version: "3.4"

services:
  producer:
    build: ./producer
  consumer:
    build: ./consumer
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

volumes:
  rabbitmqdata:
