apiVersion: apps/v1
kind: Deployment

metadata:
  name: consumer

spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      hostname: consumer
      containers:
        - name: consumer

          image: tonehmorris/rabbitmq-golang-demo:consumer
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9090

          resources: {}

      restartPolicy: Always

status: {}
