FROM rabbitmq:3.8.5-management

COPY . .
WORKDIR .
RUN apt-get update && apt-get install make \
    && cd tls-gen/basic \
    && make PASSWORD=bunnies CN=rabbitmq \
    && make verify \
    && make info \
    && chown -R rabbitmq:rabbitmq /tls-gen \
    && ls -l ./result \
    && echo 'ssl_options.password = bunnies' >> /etc/rabbitmq/rabbitmq.conf





